### ISSUE TITLE
Upload de Excel

### ISSUE THREAD

**Issue by githubmg** [githubmg/Suplementos#1]
SISTEMA DE GESTIÓN - NUEVA FUNCIONALIDAD

Se plantea la necesidad de generar una nueva funcionalidad en el sistema.

Dicha funcionalidad consiste en la posibilidad de realizar una carga masiva de ventas en el sistema, a partir de un archivo Excel, para agilizar la carga por el gran volumen de ventas que se cargan a diario. Esta operatoria ya la ha realizado personal de Sysmo directamente desde la base de datos del sistema.

El archivo debería tener un formato con las siguientes columnas (FRAN, POR FAVOR AYUDAME CHEQUEANDO QUE ESTOS SEAN TODOS LOS CAMPOS NECESARIOS PARA CARGAR LA VENTA EN CABECERA E ITEMS. CREO QUE SÍ, PORQUE YA LO HICIMOS VÍA BASE DE DATOS):

Fecha de la venta
idCliente
Monto abonado
idProducto
Cantidad
PrecioUnitario (CREO QUE NO SE USA, VALIDAR CON FRAN SI SÓLO HACE FALTA EL MONTO ABONADO.)
Subempresa

En cuanto al ID de Venta, cada registro cargado sería una venta diferente (todas las ventas contendrían un único ítem).

El sistema debería validar los datos antes de procesarlos, e informar si existe algún error o faltante de datos necesario. Validaciones a realizar serían (FRAN, AVISAME SI TE PARECE QUE HAY ALGUNA OTRA):
Fecha válida
Cliente existente
Producto existente
El resto de los datos informados con un formato válido

Si el archivo Excel no tiene errores ni faltantes, el sistema debe procesarlo, y luego informar si la carga masiva de ventas fue realizada exitosamente (idealmente, debería informar en ese mensaje de carga exitosa cuántas ventas fueron agregadas al sistema).

**Comment by nmonja** [comment]
Hola Francesca, de a poco me voy familiarizando con esto... te cuento que me dieron el ok para que avancemos con este desarrollo de carga masiva de Excel, así que adelante pequeña. Cualquier duda comentame, estamos hablando.

**Comment by githubmg** [comment]
Hola Nico

  Acá te dejo un link  a los fuentes, después los subo a github: https://dl.dropboxusercontent.com/u/14669841/Suplementos.rar

  Esto sería un ejemplo de Excel para importar ventas:
![ventas](https://cloud.githubusercontent.com/assets/8379091/4958813/a8d26e30-66b2-11e4-8357-3966ea06a1b5.png)

**Comment by nmonja** [comment]
Fran, breves consultas, ¿el excel tiene que tener fila de encabezados siempre? ¿o nunca? Otra, ¿hay que zipearlo antes de subirlo? ¿o se sube en formato Excel?

**Comment by githubmg** [comment]
Hola Nico
  El excel espera una columna de encabezado, es decir, el programa lee a partir de la segunda fila para abajo.  No hay que zipearlo, espera un archivo de tipo xls, xlsx o csv. Fijate que no te va a permitir desde el explorador de archivos subir archivos de otro tipo.

saludos

Date: Mon, 10 Nov 2014 12:29:15 -0800

**Comment by nmonja** [comment]
Perfecto Fran, lo pruebo y cualquier cosa te aviso, beso.

**Comment by nmonja** [comment]
Hola Fran. Cuando subo un archivo (ya sea un archivo sin el formato correcto, o uno tal cual me pasaste de ejemplo) me tira el siguiente error al hacer el upload:

Fatal error: Class 'ZipArchive' not found in /home/ux000486/public_html/classes/PHPExcel/Reader/Excel2007.php on line 94

¿Podrás verlo? Gracias, abrazo.

**Comment by githubmg** [comment]
¿No lo estás subiendo comprimido no?
Date: Wed,  12 Nov 2014 05:58:20 -0800

**Comment by githubmg** [comment]
Me parece que es un tema de entorno. Fijate si podés habilitar zlib en el php ini: http://www.forosdelweb.com/f18/error-libreria-phpexcel-fatal-error-class-ziparchive-not-found-762840/

**Comment by lantonelli** [comment]
Fran, 
Te copio la respuesta de dattatec
Estimado Leandro
Te comento que la misma se encuentra habilitada para todos los planes

zlib
ZLib Support    enabled
Stream Wrapper support  compress.zlib://
Stream Filter support   zlib.inflate, zlib.deflate
Compiled Version    1.2.1
Linked Version  1.2.1

Quedo a tu disposición para toda consulta adicional.

## Saludos Cordiales.

Juan Ignacio Cadierno
Soporte Técnico
DonWeb by Dattatec.com
Alojamos Sueños

**Comment by githubmg** [comment]
Chequearon lo demás q dice en el link?

zlib.output_compression = off

y

;extension=php_xsl.dll
;extension=php_zip.dll

**Comment by lantonelli** [comment]
Estimado Leandro:
Te comento que peudes verificar los modulos activos en la siguiente url 
http://ux000486.ferozo.com/info.php
zlib.output_compression = off se encuentra en off por ejemplo
Quedo a tu disposición para toda consulta adicional.

**Comment by nmonja** [comment]
¡Hola amiguitos! Mirando la última respuesta que copiaste Dodó, ¿eso quiere decir que estamos en una de esas encrucijadas en las que nada puede hacerse? ¿Cómo podemos hacer para que funque la subida de los excel con esta configuración? Pregunto porque hoy debería hablarle a esta gente. Sé que lo importante es avanzar con lo de JF, pero este módulo ya tiene el ok y pienso cobrarlo, así que avisen cualquier idea, abrazo.

**Comment by githubmg** [comment]
Estamos bastante complicados. Yo esto lo hice en la oficina y funcionaba, ahora me traje el código a casa y lo estoy haciendo funcionar también, la verdad que seguro es un tema de configuración. Me parece que el problema no es el módulo zlib, sino la dll zipArchive.

Lo que probé acá en casa y sigue funcionando es agregar la línea PHPExcel_Settings::setZipClass(PHPExcel_Settings::PCLZIP); para que la librería que lee los excel trate de usar otra cosa. Acá en casa sigo sin tener problema.

 Acá va el link del archivo para reemplazar: https://dl.dropboxusercontent.com/u/14669841/importar.php

**Comment by githubmg** [comment]
Dodó, fijate que acá en casa, en mi php info tengo un módulo zip que ellos no tienen. Veamos si pueden instalarlo, a ver si lo hacemos andar. 
Saludos
![pantalla](https://cloud.githubusercontent.com/assets/8379091/5048129/651ba85a-6c02-11e4-8ec0-46c9fb776241.png)

**Comment by githubmg** [comment]
Sí, por lo que estoy leyendo es probable que falte la libería zip.

**Comment by lantonelli** [comment]
El tema que al ser un servidor compartido, no pueden modificar la configuración. No entiendo. Es muy necesario usar Zipeo para subir el excel?

**Comment by githubmg** [comment]
Usé una librería para leer el excel, no sabría hacerlo de otra forma.

**Comment by lantonelli** [comment]
Pregunto y te contesto

**Comment by nmonja** [comment]
Que cagada. Porque aunque sea eso, no creo que dejen instalarlo...
Estoy pensando lo siguiente: a no volverse locos con este tema. Dody, si te dicen que no se puede, no hay drama. Yo hablo con ellos. Avancemos sí fuertemente con el pasaje de todo al sw de JF.
Abrazo.

**Comment by lantonelli** [comment]
Me indicaron que cambie la versión de PHP a la 5.3
Eso hice y aparece ahora ese módulo (http://ux000486.ferozo.com/info.php).
Habría que probar que nada dejó de andar.

Saludos, 
Leandro

**Comment by githubmg** [comment]
Nico ¿Probás vos directamente?

**Comment by nmonja** [comment]
¡Bien ahí muchachada! Pruebo yo, cuando volvemos de la reunión de hoy me pongo con eso Dody. Abrazo.

**Comment by githubmg** [comment]
parece  q anda eh

**Comment by nmonja** [comment]
Hola Francesca, ¿cómo va? Buenas noticias, ahora sí pude probar el módulo de importación de ventas. Funciona bien, a excepción de lo siguiente:
- Cuando fui a chequear el reporte de ganancias, pude verificar que la cantidad de items vendidos impacta bien, pero no ocurre esto con el "Total de ventas" (el importe). Las ventas importadas no están impactando bien, hacé la prueba con cualquier excel (con el que me mandaste de ejemplo si querés), revisando el "Total ventas" antes y después de importar. No sé si tendrá que ver con que no estamos tomando el precio unitario (¿no tomará de ahí ese valor?) o con alguna otra cosa, pero si corregís eso, ya estaría todo. Les voy a avisar también a ellos que esta semana vayan probando.
  Avisame Francesca, esta semana seguramente te estaré llamando para transmitirte novedades, beso.

**Comment by nmonja** [comment]
Agrego, porque sigo probando: me parece que está tomando sólo el monto de la primera de las ventas para actualizar el "Total de ventas" en el reporte de ganancias (y no los importes de todas las filas posteriores a la primera), saludos.
