### ISSUE TITLE
Observaciones 20150316

### ISSUE THREAD

**Issue by nmonja** [githubmg/Suplementos#3]
Hola Fran, no para ahora pero el miércoles si podemos vemos algo de esto, son las observaciones que me pasó la gente de Suplementos ahora que lo usan a full. Obviamente veremos cuáles hacer, y antes Dodó tiene que pasarte el último fuente actualizado. Nos hablamos pequeña:
- Agregar las cargas de ventas y compras masivas al nuevo sistema HACER ÚLTIMO
- Cambiar el predeterminado en el panel de compras de SM a MM.  HACER (ok)
- No estaría la posibilidad de agregar proveedor, producto o laboratorio desde el panel de compras, solo en sus tablas maestras particulares, ¿será posible que existan ambas opciones, como en el sitema anterior?
- Al cargar las compras, el botón de "añadir item" se corre al agregar los valores de precio unitario y la cantidad, HACER (ok)
- La tecla TAB no me permite pasar de un campo al otro
- La tecla enter no me permite añadir items sin ir a clickear el botón HACER en compras y ventas (ok)
- Los importes unitarios con decimales no leen el punto, sino la coma, y en el teclado numérico tengo punto (debo ir al teclado general a buscar la coma para que no me lea un número de 5 cifras en lugar de 3 con dos decimales).
- en el módulo de carga de compras no hay ningún lugar en donde me muestre el IMPORTE TOTAL DE LA COMPRA, que suelo mirar para comparar con mis cuentas como último control antes de aceptarlo. HACER (ok)
- Si aprieto el botón de agregar item directamente después de completar el campo de precio unitario sin hacer click afuera para que me muestre el subtotal, me tira un error, se me va a una pantalla de error, y tengo que volver para atrás.
- ¿es posible que en el sistema anterior estuviera primero el campo de precio unitario y luego el de cantidad? Porque por default parece que lo completo así, me da la sensación de que tal vez el orden era al revés. Calculo que no es mucho drama cambiarlo, pero me cambia en la agilidad del día a día. HACER (ok)

Cosas generales pendientes:
- Resolver poder poner el costo unitario a 0 sin tener que usar el 0,01
- Resolver las fórmulas de cálculo de ganancia y solución momentánea
- Depurar lista de clientes y productos (pendiente de mi envío de archivo)
- Agregar código de barras

**Comment by githubmg** [comment]
Buenísimo
¿Me recordás el usuario y clave de dhermacenter.sysmo.com.ar?

Date: Mon, 16 Mar 2015 10:02:53 -0700

**Comment by nmonja** [comment]
Dale Fran, te paso, es usuario "admin" y pass "admin"; copiá lo que
necesites, lo que sí, fijate de no tocar nada porque está en Producción.
Beso,
Lic. Nicolás Monja
15-6577-7390 - nmonja@sysmo.com.ar (mailto:nmonja@sysmo.com.ar)
    Sysmo ConsultoraSantiago del Estero 454 - 8° 33www.sysmo.com.ar
(http://www.sysmo.com.ar/) (http://www.facebook.com/sysmoconsultora) 
(http://www.linkedin.com/company/sysmo) 
(http://plus.google.com/u/0/b/114990497392421970899/114990497392421970899/posts)
---- Original Message ----

**Comment by nmonja** [comment]
En Compras, cuando agrego un ítem, el segundo me aparece seteado por default con "SM" (debe hacerlo con "MM").

**Comment by nmonja** [comment]
Quise guardar una compra, y me tiró el seguiente error:

The UPDATE statement conflicted with the FOREIGN KEY constraint "compra$compra_ibfk_1". The conflict occurred in database "wi881186_sm", table "dbo.proveedor", column 'id_proveedor'.

**Comment by nmonja** [comment]
25/03/2015: Mail de la usuaria:
Las dos cosas que me estarían haciendo falta con mayor necesidad son: agregar la opción de añadir productos y clientes/proveedores desde los procesos de venta y compra (que no esté solo en tablas maestras) y el importe de venta/compra total en el panel general de proceso (están las columnas de precio/costo unitario y monto total -que en realidad es subtotal - pero no el total de la compra/venta). Estas cosas tal vez te las dije pero no recuerdo, perdón si reitero. Lo que sí no te dije, que en realidad está desde el sistema anterior, es que al exportar un excel después de una búsqueda filtrada, debería respetar ese filtro (por ejemplo, si yo busco X cosa y me tira tres resultados, cuando exporto el excel habría de tirarme esas tres ventas, pero al contrario me exporta toda la base de datos y debo realizar el filtrado manualmente en el excel otra vez).

Fran, después que tengas lo que hoy vimos de JF, avanzamos con esto, estamos hablando, saludos.

Agrego Francesca, para que veamos la semana que viene, lo pongo ahora para no olvidarme. Lo otro importante, es esto:

Hola Nicolás, no pude el otro día escribirte lo de las fórmulas. 
Antes que nada te cuento que cambié el nombre del cliente "SM" a "SM GONZALO" para evitar confusiones al hablar del stock y esas cosas.
Deben existir en el sistema CUATRO formas de calcular la ganancia:
1) Cualquier cliente menos "SM GONZALO" (es decir, ventas de mariano a sus clientes), vendiendo productos propios (es decir, del stock mm): como es el sistema ahora: 
precio menos costo = ganancia

2) Cualquier cliente menos "SM GONZALO" (es decir, ventas de mariano a sus clientes), vendiendo productos de miami (es decir del stock sm): dejaríamos de subir las compras de dicho stock a costo 0 y pondríamos el costo real. Por lo tanto en estos casos la fórmula sería:
[(precio menos costo) dividido 2] menos costo = ganancia

3) Únicamente el cliente "SM GONZALO" al vender productos de miami (es decir, del stock sm): 
[(precio menos costo) dividido 2] más costo = ganancia

4) Únicamente el cliente "SM GONZALO" al vender productos de mariano (es decir, del stock mm): 
[(precio menos costo) dividido 2] menos costo = ganancia

**Comment by nmonja** [comment]
IMPORTANTE: PARA CUALQUIER PRODUCTO QUE SE VENDA, EL SISTEMA DEBE VERIFICAR LAS UNIDADES NO ASIGNADAS DEL STOCK QUE CORRESPONDA (SM SI LA VENTA ES DE SM, Y MM SI LA VENTA ES DE MM).
