### ISSUE TITLE
PENDIENTES SM CON PRIORIDADES ACTUALIZADO 20150327

### ISSUE THREAD

**Issue by nmonja** [githubmg/Suplementos#4]
Hola Fran, ¿todo ok? Bueno, tal como hablamos y después de todo el simposio que tuve con la gente de SM hoy, te paso en limpio lo que tendríamos que hacer:

A) TEMA CÁLCULO DE GANANCIAS. PRIORIDAD: MUY ALTA

Por un lado, algo que creo nunca tuvimos en cuenta pero, tal como te contaba por teléfono, para ellos estaba sobreentendido: Para cualquier venta de un producto, para calcular el costo el sistema debe verificar las unidades no asignadas de las compras de ese producto cronológicamente (tal cual hace ahora), pero si la venta es SM debe revisar las unidades no asignadas de las compras que sean SM; y si la venta es MM, debe revisar las unidades no asignadas de las compras que sean MM; hoy no hace este último chequeo. Esto es fundamental.

Además, y relacionado con esto, deben existir en el sistema CUATRO formas de calcular la ganancia:

1) Venta realizada para cualquier cliente menos "SM GONZALO" (es decir, ventas de mariano a sus clientes), vendiendo productos propios (es decir, del stock mm): igual que como es en el sistema ahora: 
precio menos costo = ganancia

2) Venta realizada para cualquier cliente menos "SM GONZALO" (es decir, ventas de mariano a sus clientes), vendiendo productos de miami (es decir del stock sm):  en estos casos la fórmula sería:
[(precio menos costo) dividido 2] menos costo = ganancia

3) Ventas únicamente al cliente "SM GONZALO" al vender productos de miami (es decir, del stock sm): 
[(precio menos costo) dividido 2] más costo = ganancia

4) Ventas únicamente al cliente "SM GONZALO" al vender productos de mariano (es decir, del stock mm): 
[(precio menos costo) dividido 2] menos costo = ganancia

Puede parecer bastante complejo pero son fórmulas al fin y al cabo. Lo que también vamos a tener que modificar, se me ocurre, como consecuencia de estas fórmulas, es el Reporte de Ganancias que tienen, para poder mostrar todo esto.

B) MODIFICACIONES RELACIONADAS CON LO OPERATIVO. PRIORIDAD: ALTA PERO NO TANTO COMO EL PUNTO A):

1) Combo de laboratorio (al agregar productos): ordenar por orden alfabético. (OK) (CHECK)

2) En las Ventas, al cargar una nueva venta, poner el campo "Monto Total" encima del campo "Cantidad". (OK) (CHECK)

3) En las Ventas, al cargar una nueva la opción por defecto del campo "Subempresa" es MM. Eso es correcto. Pero cuando agrego un ítem, el segundo (y los sucesivos) muestran por defecto la opción SM. Debe ser MM, corregir. (OK) (CHECK)

4) En Ventas y Compras, que figure el IDVenta y el IDCompra en todas las compras y ventas (para las que tienen más de un ítem, hoy figuran sólo en el primer ítem); modificar eso, pero que se mantenga que sólo el primer ítem de cada venta o compra esté en negrita (tal como está ahora). (OK) (CHECK)

5) Ventas y compras: al querer borrar una venta o compra, que el sistema muestre la pregunta "¿Realmente desea borrar esta venta" (o compra si es una compra), pudiendo el usuario aceptar y borrarla, o cancelar. Esto es para que los usuarios no hagan cagadas. (OK) (CHECK)

6) No estaría la posibilidad de agregar proveedor, producto o laboratorio desde el panel de compras, solo en sus tablas maestras particulares, ¿será posible que existan ambas opciones, como en el sistema anterior? (ESTO LO AGREGUÉ PORQUE YA LO ESTÁS HACIENDO PEQUEÑA)
(OK)

Cuando agrego un proveedor desde una Compra, me tira el siguiente error:

Server Error in '/' Application.

Cannot insert the value NULL into column 'id_persona', table 'wi881186_sm.dbo.proveedor'; column does not allow nulls. INSERT fails.
The statement has been terminated.

Cuando quiero agregar un nuevo producto, me tira el combo de laboratorios vacío y no me permite escribir ninguno. Sólo si agrego un nuevo laboratorio desde ahí, me muestra los demás.

C) OTRAS MODIFICACIONES. PRIORIDAD: MEDIA/BAJA

1) Resolver poder poner el costo unitario a 0 sin tener que usar el 0,01

2) Depurar lista de clientes y productos (pendiente de mi envío de archivo)

3) Agregar código de barras

4) No funciona bien el borrado de Usuarios en el módulo de Usuarios (OK) (CHECK)

Eso es todo, por favor cualquier consulta chiflame, sobre todo del tema ganancias y cómo mostrarlo. Estamos hablando, beso,
Nico

**Comment by githubmg** [comment]
¡Fran querida! Sí que hizo ruido, me han consultado por un caso de ese tipo, pasa que entre tanto revuelo quedó en la nada... bien que te diste cuenta. Seguí mirando lo que te pasé acerca del cálculo de ganancias, y cualquier cosa que vayas viendo o consulta que tengas por favor avisame, yo hoy y mañana voy a estar laburando así que lo que sea que quieras saber, estoy para responderte pequeña.

Nico por las dudas te comento: había un error muy grave en el cálculo de ganancias: cuando no existía ninguna compra de un producto, en lugar de asignar el costo 0, asignaba el costo de la última cosa comprada, porque faltaba hacer un where para que la compra fuera del mismo producto que la venta.Es decir, faltaba agregar AndAlso ic.id_producto = ivDB.id_producto
Te muestro el código a ver si lo entendés mejor. Ahora ya lo corregí, pero tal vez eso estaba haciendo un ruido estrepitoso.
'Las compras cargadas en la base NO son suficientes para saldar la venta 
            'Asigno el costo más reciente o 0 si no existe compra anterior a la venta
            Try
                Dim costoMasReciente = (From ic In db.item_compras
                                        Join c In db.compras On ic.id_compra Equals c.id_compra
                                        Where ic.compra.fecha <= ivDB.venta.fecha AndAlso
                                              ic.id_producto = ivDB.id_producto AndAlso
                                              c.activo = 1
                                        Order By ic.compra.fecha, ic.id_item_compra Descending
                                        Select ic.precio_unitario).First()
                ivDB.costo = costoMasReciente \* ivDB.cantidad
            Catch
                'No existe ninguna compra cargada
                ivDB.costo = 0
            End Try

Date: Fri, 27 Mar 2015 11:29:22 -0700
