### ISSUE TITLE
Temas Suplementos SM 20150429

### ISSUE THREAD

**Issue by nmonja** [githubmg/Suplementos#6]
FRAN, ACTUALIZO ESTO DE ACUERDO A LO HABLADO HOY CON MARIANO, TAL COMO TE DETALLÉ POR TELÉFONO, BESO:

Hola Fran. Necesito hablar contigo pequeña, tuve novedades importantes, te voy contando:
- Aceptaron finalmente mandar todo lo viejo a Histórico. Es decir, el procedimiento va a ser el siguiente:
  - Mañana jueves, a última hora, ellos me van a mandar un Excel con todos los productos que tienen en stock, que cantidad de unidades y el costo de las mismas, tanto para lo de Mariano como para lo de Gonzalo.
- Entre hoy y el lunes, tenemos que preparar los cambios para mover todas las compras y ventas viejas de ellos a una tabla histórica; el día lunes 04/05, a la mañana, tenemos que actualizar su sistema con los cambios, y cargar las compras correspondientes al Excel que nos van a pasar.
- Por otro lado, muy contentos con el nuevo módulo de rendiciones. Creíamos que ya estaba y el lunes terminábamos este penoso sistema. No obstante, la mala noticia del día es que se dieron cuenta de algo grave que no habían tenido en cuenta ellos:
  - Desde hace unos meses, implementaron lo siguiente: cada vez que Gonzalo hace una venta del stock de Mariano (MM) el costo de esa venta no debe ser el correspondiente a la última compra con unidades no asignadas; sino que debe salir de un campo más de la tabla producto; dicho dato puede ser cargado directamente por ellos, o bien cargarlo directamente nosotros a partir de un Excel que nos pasen cada vez que se modifique, lo que sea más práctico y fácil pequeña.
    Lo que Dodó me indicaba que habría que hacer, por supuesto charlándolo primero con vos, es lo siguiente: cada vez que se haga una venta, que busque la compra más antigua con unidades no asignadas; pero, si es una venta de Gonzalo que salga del stock de Mariano, debe "pisar" el costo con el costo cargado para ese producto.
    Esto no se los prometí obviamente para el lunes, por lo cual recién usarían el módulo de rendiciones cuando esté listo, pero cuánto antes esté listo nos sacamos todo esto de encima Fran...

El lunes, ¿podés venirte a Sysmo así nos das una mano para actualizar los cambios en el Sistema?

Te hablo en un rato pequeña, por favor démosle prioridad a esta mierda interminable a ver si la sacamos de una vez, beso grande,
Nico

**Comment by githubmg** [comment]
Hola Nico
 ¿Qué hacés? Justo estaba en reunión en UBA. Yo voy preparando todo, incluyendo la subida de un Excel hipotético y el viernes cuando nos juntamos lo subimos a test ¿Te parece?
  El cambio de costeo no parece tan complicado, eso sí, es pesadísimo a nivel búsqueda. 

Date: Wed, 29 Apr 2015 09:32:57 -0700

**Comment by nmonja** [comment]
Hola Fran, buenísimo. Escuchame, ¿tuviste en cuenta que el viernes es
feriado (01/05)? No tengo problema en juntarme si eso ayuda a ganar tiempo,
pero avisame qué preferís; sino yo había pensado en que vos avanzaras,
yo probara en test a medida que me subieras (no me voy a ningún lado el
finde) y el lunes te vinieras y lo hiciéramos todo en Producción.
En un ratito te pego un llamado y hablamos bien, beso,
Lic. Nicolás Monja
15-6577-7390 - nmonja@sysmo.com.ar (mailto:nmonja@sysmo.com.ar)
    Sysmo ConsultoraCorrientes 821 - 6° "A" (C.A.B.A.)www.sysmo.com.ar
(http://www.sysmo.com.ar/) (http://www.facebook.com/sysmoconsultora) 
(http://www.linkedin.com/company/sysmo) 
(http://plus.google.com/u/0/b/114990497392421970899/114990497392421970899/posts)
---- Original Message ----
